name: Bug Report
description: Something doesn't seem correct and it might be a bug
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug description / Bug秒速
      description: |
        A clear and concise description of what the bug is.
        Is it a game crash, an unexpected behavior, or has something gone wrong?
        If applicable, add screenshots to help explain the bug.
        -------------------------------------------------------------------------
        用简洁的语言描述这是一个怎么样的bug！
        是游戏崩溃、发生意料之外的情况，或者出了别的问题？
        如果可以请添加截图或者 log
      placeholder: Tell us what you see! / 告诉我们你看到了什么问题
    validations:
      required: true

  - type: textarea
    id: to-reproduce
    attributes:
      label: Steps to reproduce / 复现不走
      description: | 
        Steps to reproduce the bug.
        ---------------------------
        如何复现这个bug
      placeholder: |
        (Example)
        1. Create a world
        2. Wait until midnight
        3. Hug a creeper
        -----------------------
        (例子)
        1. 创建一个世界
        2. 等到午夜
        2. 拥抱一只苦力怕
    validations:
      required: true

  - type:  textarea
    id: expected-behavior
    attributes:
      label: Expected behavior / 预期行为
      description: |
        What did you expect to happen?
        ------------------------------
        你想要发生什么?
      placeholder: |
        (Example / 例子)
        The creeper explodes
        苦力怕发生爆炸
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior / 实际情况
      description: |
        What actually happened?
        -------------------------
        实际发生了什么?
      placeholder: |
        (Example / 例子)
        The creeper launches itself into the sky
        苦力怕飞上了天空

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs / 相关日志
      description: |-
        If it's a crash, send the corresponding Minecraft log in the `logs` folder, or crash report in the `crash-reports` folder, here.
        Please upload the log file as an attachment, or upload the log to [pastebin](https://pastebin.com/) / [mclo.gs](https://mclo.gs/) and paste the url here.
        Please refrain from pasting the entire log file directly.
        Leave empty if there is none.
        --------------------------------------------------
        如果发生了崩溃, 在这里放入位于`logs`文件夹的Minecraft的日志文件, 或位于`crash-reports`文件夹的崩溃报告
        请作为附件上传日志文件, 或者上传日志文件到 [pastebin](https://pastebin.com/) / [mclo.gs](https://mclo.gs/) 然后复制链接到此处.
        **请作为附件上传而不是粘贴整个日志文件到此处**
        如果没有请留空
      placeholder: https://pastebin.com/

  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft version / Minecraft版本
      description: |
        The Minecraft version(s) where this bug occurs in.
        你在哪个Minecraft触发了这个bug
      placeholder: 1.20.1
    validations:
      required: true

  - type: input
    id: mod-version
    attributes:
      label: Mod version / Mod版本
      description: |
        The Mod version(s) where this bug occurs in.
        你使用哪个版本的mod触发了bug
      placeholder: 1.1.3
    validations:
      required: true

  - type: textarea
    id: other-information
    attributes:
      label: Other information / 其他信息
      description: |
        Other useful information to this bug report, e.g. other related mod version(s). Leave empty if there is none.
        如果有其他有用信息补充, 你可以写在这. 例如: 是否安装了其他mod / 修改了文件. 如果没有请留空
      placeholder: The issue only occurs if the player is in survival mode

  - type: checkboxes
    id: check-list
    attributes:
      label: Check list
      options:
        - label: I have verified that the issue persists in the latest version of the mod. / 该mod版本的问题在最新版本的mod中依旧存在
          required: true
        - label: I have searched the existing issues and confirmed that this is not a duplicate. / 我查看了现有issues并确保该问题不是重复的
          required: true