name: build
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      release:
        type: boolean
        required: false
        description: ''
        default: false
      target_subproject:
        description: The subproject name of the specified Minecraft version to be built. Leave it empty to build all
        type: string
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check out
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache gradle files
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./.gradle/loom-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle', 'gradle.properties', '**/*.accesswidener') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew remapJar

      - name: Upload JAR file
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: versions/*/build/libs/

  summary:
    runs-on: ubuntu-22.04
    needs:
      - build

    steps:
      - uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: build-artifacts

      - name: Make build summary
        run: python3 .github/workflows/scripts/summary.py
        env:
          TARGET_SUBPROJECT: ${{ inputs.target_subproject }}